from typing import Dict, Any, Optional
from langchain_core.tools import tool
from langchain.agents import create_agent 
from langchain_google_genai import ChatGoogleGenerativeAI
import json
import logging
import sys
from fastapi import HTTPException
# from langchain.chat_models import ChatOpenAI
import os

# Add project root to sys.path so relative package imports work
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from backend.app import models, schemas, database
from backend.app.routers import cart, product, categories, search
from dotenv import load_dotenv
load_dotenv()

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logger = logging.getLogger(__name__)

def get_system_prompt(user_id: int) -> str:
    return f"""You are a voice-based shopping cart assistant.

You are currently serving user_id = {user_id}. Always use this user_id when calling tools.

Your job is to help users manage their shopping cart by deciding when to use tools.

You can:
- Search for products
- Add items to the cart
- Remove items from the cart
- Update item quantities
- View cart contents
- Calculate total cost

Rules:
- Use tools when an action is required.
- Do NOT make up product IDs.
- Always use user_id = {user_id} for cart operations.
- Ask a clarifying question if required information is missing.
- When no tool is needed, respond directly to the user.
"""


@tool
def add_to_cart(user_id: int, product_id: int, quantity: int = 1) -> str:
    """Add a product to the user's cart.

    If the product already exists in the cart, the quantity is increased.
    If the product does not exist in the cart, a new cart entry is created.

    Args:
        user_id: The ID of the user whose cart to modify.
        product_id: The ID of the product to add.
        quantity: The number of units to add (default 1).

    Returns:
        A string message describing the result of the operation.
    """
    db = database.SessionLocal()
    try:
        cart_item = schemas.CartCreate(product_id=product_id, quantity=quantity)
        result = cart.add_product_to_cart(cart_item=cart_item, db=db, user_id=user_id)
        return f"Added product {product_id} (x{quantity}) to the cart. Current quantity: {result.quantity}."
    except HTTPException as e:
        return f"Error: {e.detail}"
    except Exception as e:
        db.rollback()
        logger.error(f"add_to_cart failed: {e}")
        return f"Error: Failed to add product to cart — {e}"
    finally:
        db.close()
        
        
@tool
def search_products(query: str) -> str:
    """Search for products based on a query string.

    Args:
        query: The search query to find matching products.
        
    Returns:
        A string representation of the search results, including product names and IDs."""
    db = database.SessionLocal()
    try:
        results = search.search_products(query=query, db=db)
        if not results:
            return f"No products found matching '{query}'."
        return json.dumps([{"id": p.id, "name": p.name, "price": float(p.price), "stock": p.stock} for p in results])
    except Exception as e:
        logger.error(f"search_products failed: {e}")
        return f"Error: Failed to search products — {e}"
    finally:
        db.close()
    
def create_cart_agent(user_id: int):
    """Create a langgraph react agent for managing the shopping cart.

    Args:
        user_id: The ID of the user for whom to create the agent.
    Returns:
        A compiled langgraph agent.
    """
    tools = [add_to_cart, search_products]

    llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.2)
    
    agent = create_agent(model=llm, tools=tools, system_prompt=get_system_prompt(user_id))
    return agent

class CartAgent:
    def __init__(self, user_id: int):
        self.user_id = user_id
        self.agent = create_cart_agent(user_id=user_id)

    def __call__(self, user_input: str) -> str:
        """Process user input through the agent.

        Args:
            user_input: The raw input from the user.
        Returns:
            The response generated by the agent.
        """
        try:
            result = self.agent.invoke(
                {"messages": [{"role": "user", "content": user_input}]}
            )
            # Extract the last AI message from the response
            for msg in reversed(result["messages"]):
                if hasattr(msg, "content") and msg.content and not getattr(msg, "tool_calls", None):
                    return msg.content
            return "No response generated."
        except Exception as e:
            logger.error(f"CartAgent.__call__ failed: {e}")
            return f"Error: Failed to process input — {e}"      
        
if __name__ == "__main__":
    # Example usage
    user_id = 1  # Replace with actual user ID
    cart_agent = CartAgent(user_id=user_id)
    
    # Simulate user input
    user_input = "I want to add 2 units of product ID 5 to my cart."
    response = cart_agent(user_input=user_input)
    print(response)